apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "{{ name }}"
  description: Python service created via Backstage
  annotations:
    github.com/project-slug: "nishank841/{{ name }}"
spec:
  type: service
  lifecycle: experimental
  owner: user:guest

