flyway.url=jdbc:sqlserver://localhost:1433;databaseName=LearnSQL;encrypt=true;trustServerCertificate=true
flyway.user=sa
flyway.password=StrongP@ssw0rd!
flyway.locations=filesystem:flyway/sql
flyway.baselineOnMigrate=true
flyway.validateMigrationNaming=true

